node{
  stage('SCM Checkout'){
    def mvnHome = tool name: 'Maven3', type: 'maven'
    
    git 'https://github.com/shashank-1-1/Test_/tree/master/my-app-master'
  }
  stage('Compile-Package'){
    def mvnHome = tool name: 'Maven3', type: 'maven'
    sh "${mvnHome}/bin/mvn package"
  }
}
      
